# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for the Krylov exponential propagator (propagator.rs).

Math anchor: the semi-discrete DG system is the linear ODE dy/dt = A*y, whose
exact propagator over a step h is the matrix exponential exp(h*A). The Krylov
integrator `expmv(matvec, v, h, m)` forms the action exp(h*A)*v in an m-step
Arnoldi subspace; for an n-dimensional system a Krylov dimension m >= n spans
the whole space, so the projection is exact (up to the dense exp(h*H_m) and
round-off). This test pins that.

Operator A: a small, dense, SKEW-SYMMETRIC wave operator

        A = [[ 0, -L],
             [ L,  0]]          L = symmetric tridiagonal (discrete -Laplacian)

with L = tridiag(-1, 2, -1) on 3 nodes, so n = 6. Skew symmetry puts every
eigenvalue on the imaginary axis: the dynamics are purely oscillatory and the
Euclidean norm of y is conserved, exactly the energy-conserving regime the
propagator must reproduce. A is dense in its (1,2)/(2,1) blocks, so the Arnoldi
process genuinely fills the subspace rather than collapsing on an invariant
coordinate axis.

Reference exp(h*A)*v0 is computed by EXACT sympy matrix exponentiation,
(h*A).exp(), then evaluated at high precision (30 digits) and rounded to f64.
The Rust test feeds the same A (as a matrix-free matvec), v0 and h into the
real `expmv` and asserts it matches this reference, for several step sizes.
"""
from __future__ import annotations

import os

import sympy as sp

# ---- the operator A (6x6 skew-symmetric wave operator) -------------------
L = sp.Matrix([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
Z = sp.zeros(3, 3)
A = sp.Matrix(sp.BlockMatrix([[Z, -L], [L, Z]]))
N = A.shape[0]
assert (A + A.T) == sp.zeros(N, N), "A must be skew-symmetric"

# ---- a deterministic, non-symmetric test vector --------------------------
V0 = sp.Matrix([sp.Rational(i + 1, 7) for i in range(N)])

# ---- step sizes to pin ---------------------------------------------------
STEPS = [sp.Rational(1, 10), sp.Rational(3, 10), sp.Rational(1, 1)]

DIGITS = 30


def f64(x: sp.Expr) -> str:
    """Round-trippable f64 literal from an exact sympy expression."""
    return repr(float(x.evalf(DIGITS)))


def flat_array(name: str, vals: list[str]) -> str:
    body = ", ".join(vals)
    return f"const {name}: [f64; {len(vals)}] = [{body}];"


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(
        os.path.join(
            here,
            "..",
            "..",
            "crates",
            "rapidfem-td",
            "tests",
            "propagator_expm_test.rs",
        )
    )

    a_flat = [f64(A[i, j]) for i in range(N) for j in range(N)]
    v0_flat = [f64(V0[i]) for i in range(N)]

    cases = []  # (h_literal, h_name, ref_name, ref_flat)
    for k, h in enumerate(STEPS):
        E = (h * A).exp()
        ref = E * V0
        ref_flat = [f64(ref[i]) for i in range(N)]
        cases.append((repr(float(h)), f"H{k}", f"REF{k}", ref_flat))

    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    lines.append("//")
    lines.append(
        "// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors"
    )
    lines.append("//")
    lines.append(
        "// GENERATED by derivations/td_dg/emit_propagator_golden.py "
        "- do not edit."
    )
    lines.append(
        "// Golden reference for the Krylov exponential propagator "
        "(propagator.rs)."
    )
    lines.append("//")
    lines.append(
        "// dy/dt = A*y has the EXACT propagator exp(h*A). A is a 6x6"
    )
    lines.append(
        "// skew-symmetric wave operator [[0,-L],[L,0]], L = tridiag(-1,2,-1),"
    )
    lines.append(
        "// so every eigenvalue is on the imaginary axis (oscillatory, energy-"
    )
    lines.append(
        "// conserving). The reference exp(h*A)*v0 is computed by EXACT sympy"
    )
    lines.append(
        "// matrix exponentiation, (h*A).exp(), at 30-digit precision. For a"
    )
    lines.append(
        "// 6-dim system a Krylov dimension m >= 6 spans the whole space, so the"
    )
    lines.append(
        "// Arnoldi projection is exact bar the dense exp(h*H_m) and round-off."
    )
    lines.append("")
    lines.append("use rapidfem_td::propagator::expmv;")
    lines.append("")
    lines.append(f"const N: usize = {N};")
    lines.append("")
    lines.append("// Row-major 6x6 operator A.")
    lines.append(flat_array("A", a_flat))
    lines.append("// Test vector v0.")
    lines.append(flat_array("V0", v0_flat))
    lines.append("")
    for h_lit, h_name, ref_name, ref_flat in cases:
        lines.append(f"const {h_name}: f64 = {h_lit};")
        lines.append(flat_array(ref_name, ref_flat))
    lines.append("")
    lines.append("/// Matrix-free A*x for the dense row-major A above.")
    lines.append("fn matvec(x: &[f64]) -> Vec<f64> {")
    lines.append("    let mut ax = vec![0.0; N];")
    lines.append("    for i in 0..N {")
    lines.append("        let mut s = 0.0;")
    lines.append("        for j in 0..N {")
    lines.append("            s += A[i * N + j] * x[j];")
    lines.append("        }")
    lines.append("        ax[i] = s;")
    lines.append("    }")
    lines.append("    ax")
    lines.append("}")
    lines.append("")
    lines.append("fn rel_err(got: &[f64], want: &[f64]) -> f64 {")
    lines.append("    let num: f64 = got")
    lines.append("        .iter()")
    lines.append("        .zip(want)")
    lines.append("        .map(|(g, w)| (g - w).powi(2))")
    lines.append("        .sum::<f64>()")
    lines.append("        .sqrt();")
    lines.append(
        "    let scale: f64 = want.iter().map(|w| w * w).sum::<f64>().sqrt();"
    )
    lines.append("    num / scale.max(1e-300)")
    lines.append("}")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn propagator_matches_exact_matrix_exponential() {")
    lines.append("    // Krylov dimension covering the whole 6-dim space makes")
    lines.append("    // the projection exact; m = 12 (>= N) with the early")
    lines.append("    // lucky-breakdown stop runs at most N steps anyway.")
    lines.append("    let m = 12;")
    for h_name, ref_name in [(c[1], c[2]) for c in cases]:
        lines.append("")
        lines.append(f"    let got = expmv(matvec, &V0, {h_name}, m);")
        lines.append(f"    let err = rel_err(&got, &{ref_name});")
        lines.append(
            f'    eprintln!("h = {{:.3}}: rel err vs exp(hA)*v0 = {{:.2e}}", '
            f"{h_name}, err);"
        )
        lines.append(
            f'    assert!(err < 1e-10, "h = {{}}: rel err {{:.2e}}", '
            f"{h_name}, err);"
        )
    lines.append("}")
    lines.append("")

    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
