# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for the DGTD reference element (dg_basis.rs).

Reproduces, with EXACT rational sympy arithmetic, the nodal-DG reference
operators on the unit tetrahedron used by `rapidfem_td::dg_basis`:

  reference tet : vertices (0,0,0),(1,0,0),(0,1,0),(0,0,1)  (r,s,t >= 0,
                  r+s+t <= 1)
  monomials     : exponents (a,b,c), grouped by total degree <= p, in the
                  SAME order the Rust `monomials()` emits them
  nodes         : equispaced (i,j,k)/p with i+j+k <= p, SAME order as the
                  Rust `equispaced_nodes()`
  Vandermonde   : V[node, mono] = mono(node),  C = V^-1
  Gram          : G[m,n] = integral_ref ( mono_m * mono_n )
                         = a! b! c! / (a+b+c+3)!     (closed form)
  mass          : M = C^T G C
  diff matrices : Dr = Vr C, Ds = Vs C, Dt = Vt C, where
                  Vd[node, mono] = (d mono / d x_d)(node)

The generated cargo test calls the real Rust `ReferenceElement::new(p)` for
each order and asserts mass / diff_r / diff_s / diff_t entrywise against these
exact values.
"""
from __future__ import annotations

import os

import sympy as sp

# Orders to pin. p=1 -> Np=4, p=2 -> Np=10, p=3 -> Np=20.
ORDERS = [1, 2, 3]


def monomials(p: int) -> list[tuple[int, int, int]]:
    """Exponents (a,b,c) of total degree <= p, matching the Rust ordering."""
    v: list[tuple[int, int, int]] = []
    for deg in range(p + 1):
        for a in range(deg + 1):
            for b in range(deg - a + 1):
                v.append((a, b, deg - a - b))
    return v


def equispaced_nodes(p: int) -> list[tuple[sp.Rational, sp.Rational, sp.Rational]]:
    """Equispaced nodes (i,j,k)/p, matching the Rust ordering (exact)."""
    v = []
    for i in range(p + 1):
        for j in range(p - i + 1):
            for k in range(p - i - j + 1):
                v.append(
                    (sp.Rational(i, p), sp.Rational(j, p), sp.Rational(k, p))
                )
    return v


def mono_integral(a: int, b: int, c: int) -> sp.Rational:
    """Exact integral of r^a s^b t^c over the unit reference tet."""
    return sp.factorial(a) * sp.factorial(b) * sp.factorial(c) / sp.factorial(
        a + b + c + 3
    )


def eval_mono(m, x) -> sp.Expr:
    return x[0] ** m[0] * x[1] ** m[1] * x[2] ** m[2]


def eval_mono_d(m, x, axis: int) -> sp.Expr:
    e = m[axis]
    if e == 0:
        return sp.Integer(0)
    d = list(m)
    d[axis] -= 1
    return e * eval_mono(d, x)


def element_matrices(p: int):
    """Return exact (mass, diff_r, diff_s, diff_t) as sympy Matrices."""
    monos = monomials(p)
    nodes = equispaced_nodes(p)
    n = len(monos)
    assert n == len(nodes), "monomial / node count mismatch"

    V = sp.Matrix(n, n, lambda i, j: eval_mono(monos[j], nodes[i]))
    C = V.inv()

    G = sp.Matrix(
        n,
        n,
        lambda i, j: mono_integral(
            monos[i][0] + monos[j][0],
            monos[i][1] + monos[j][1],
            monos[i][2] + monos[j][2],
        ),
    )
    mass = C.T * G * C

    Vr = sp.Matrix(n, n, lambda i, j: eval_mono_d(monos[j], nodes[i], 0))
    Vs = sp.Matrix(n, n, lambda i, j: eval_mono_d(monos[j], nodes[i], 1))
    Vt = sp.Matrix(n, n, lambda i, j: eval_mono_d(monos[j], nodes[i], 2))
    diff_r = Vr * C
    diff_s = Vs * C
    diff_t = Vt * C
    return mass, diff_r, diff_s, diff_t


def f64(v) -> str:
    return f"{float(sp.N(v, 25)):.17e}"


def emit_flat(name: str, M: sp.Matrix, n: int) -> str:
    """Row-major flat [f64; n*n] literal, matching the Rust Vec layout."""
    entries = ", ".join(f64(M[i, j]) for i in range(n) for j in range(n))
    return f"const {name}: [f64; {n * n}] = [{entries}];\n"


HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/td_dg/emit_dg_basis_golden.py — do not edit.
// Golden reference-element operators for the nodal DGTD basis (dg_basis.rs),
// from EXACT rational sympy arithmetic on the unit tetrahedron:
//   mass  M = C^T G C,  C = V^-1,  G[m,n] = a!b!c!/(a+b+c+3)!
//   diff  Dr/Ds/Dt = V_d C  (exact monomial derivatives in the nodal basis)
// Pins what the Rust `ReferenceElement::new(p)` constructor computes,
// entrywise, for p = 1, 2, 3.

use rapidfem_td::dg_basis::ReferenceElement;

/// Max entrywise absolute difference divided by the max magnitude in the
/// golden matrix (global relative error).
fn max_rel_err(got: &[f64], want: &[f64]) -> f64 {
    assert_eq!(got.len(), want.len(), "length mismatch");
    let mut num = 0.0_f64;
    let mut scale = 1e-300_f64;
    for (g, w) in got.iter().zip(want.iter()) {
        scale = scale.max(w.abs());
        num = num.max((g - w).abs());
    }
    num / scale
}
"""


def emit_case(p: int) -> str:
    mass, dr, ds, dt = element_matrices(p)
    n = mass.shape[0]
    out = f"\n// ===== order p = {p}  (Np = {n}) =====\n"
    out += emit_flat(f"MASS_P{p}", mass, n)
    out += emit_flat(f"DR_P{p}", dr, n)
    out += emit_flat(f"DS_P{p}", ds, n)
    out += emit_flat(f"DT_P{p}", dt, n)
    out += f"""
#[test]
fn dg_basis_matches_derivation_p{p}() {{
    let re = ReferenceElement::new({p});
    assert_eq!(re.n_nodes, {n}, "Np for p={p}");
    let m_err = max_rel_err(&re.mass, &MASS_P{p});
    let dr_err = max_rel_err(&re.diff_r, &DR_P{p});
    let ds_err = max_rel_err(&re.diff_s, &DS_P{p});
    let dt_err = max_rel_err(&re.diff_t, &DT_P{p});
    eprintln!(
        "p={p}: max rel err  M {{:.2e}}  Dr {{:.2e}}  Ds {{:.2e}}  Dt {{:.2e}}",
        m_err, dr_err, ds_err, dt_err
    );
    assert!(m_err < 1e-9, "mass mismatch (p={p}): {{:.2e}}", m_err);
    assert!(dr_err < 1e-9, "diff_r mismatch (p={p}): {{:.2e}}", dr_err);
    assert!(ds_err < 1e-9, "diff_s mismatch (p={p}): {{:.2e}}", ds_err);
    assert!(dt_err < 1e-9, "diff_t mismatch (p={p}): {{:.2e}}", dt_err);
}}
"""
    return out


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out_path = os.path.join(
        repo, "crates", "rapidfem-td", "tests", "dg_basis_golden_test.rs"
    )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    body = HEADER
    for p in ORDERS:
        body += emit_case(p)
        print(f"emitted order p={p}")
    with open(out_path, "w") as fh:
        fh.write(body)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
