# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for the DGTD physical curl operator (rhs.rs).

Pins `rapidfem_td::rhs::element_curl` to EXACT polynomial differentiation:
for a known vector field E whose components are polynomials of total degree
<= p in PHYSICAL coordinates, sampled at the DG nodes of a SPECIFIC physical
tetrahedron, the discrete curl produced by the operator must equal the exact
analytic curl(E) (a lower-degree polynomial) sampled at the same nodes.

Why it is exact: the reference->physical map is affine, so a physical
polynomial of degree d pulls back to a reference polynomial of the same
degree d; the nodal-DG differentiation matrices Dr,Ds,Dt are exact for
reference polynomials up to degree p, and the constant Jacobian metric
J^-1 converts the reference derivatives into physical ones with no error.
Hence the operator reproduces curl(E) to rounding.

Conventions matched to the Rust code (read, not assumed):
  reference tet : vertices (0,0,0),(1,0,0),(0,1,0),(0,0,1)  (dg_basis.rs)
  nodes         : equispaced (i,j,k)/p, SAME order as `equispaced_nodes()`
  field layout  : node-major, field[node*3 + comp], comp = x,y,z  (rhs.rs)
  curl output   : same layout, out[node*3 + comp]
  Jacobian      : J columns are v1-v0, v2-v0, v3-v0  (geom_factors.rs),
                  d/dx_phys = sum_k (J^-1)[k][phys] d/dxi_k.

The generated cargo test builds the real `ReferenceElement::new(p)` and
`GeometricFactors::for_tet(TET)`, feeds the nodal field into the real
`element_curl`, and asserts it reproduces the exact curl nodally.
"""
from __future__ import annotations

import os

import sympy as sp

# Element order to pin. p=2 -> Np=10; the field below is degree <= 2.
P = 2

# A concrete, generic physical tetrahedron (sheared/scaled/translated, so the
# Jacobian metric is genuinely exercised, not the identity). Rational so the
# pulled-back arithmetic stays exact in sympy.
TET = [
    (sp.Rational(1), sp.Rational(0), sp.Rational(0)),
    (sp.Rational(2), sp.Rational(1, 2), sp.Rational(0)),
    (sp.Rational(1, 2), sp.Rational(2), sp.Rational(3, 10)),
    (sp.Rational(0), sp.Rational(1, 5), sp.Rational(3)),
]

x, y, z = sp.symbols("x y z")

# Known vector field E(x,y,z); every component is degree <= 2 = p in the
# PHYSICAL coordinates, so the operator differentiates it exactly.
E = [
    2 * x * y + 3 * y * z - z**2 + x,        # Ex
    x**2 - 4 * x * z + 2 * y**2 + z,         # Ey
    5 * y**2 + x * z - 2 * x**2 + y,         # Ez
]

# Exact analytic curl: (dEz/dy - dEy/dz, dEx/dz - dEz/dx, dEy/dx - dEx/dy).
CURL = [
    sp.diff(E[2], y) - sp.diff(E[1], z),
    sp.diff(E[0], z) - sp.diff(E[2], x),
    sp.diff(E[1], x) - sp.diff(E[0], y),
]


def equispaced_nodes(p: int):
    """Equispaced nodes (i,j,k)/p, matching the Rust ordering (exact)."""
    v = []
    for i in range(p + 1):
        for j in range(p - i + 1):
            for k in range(p - i - j + 1):
                v.append(
                    (sp.Rational(i, p), sp.Rational(j, p), sp.Rational(k, p))
                )
    return v


def phys_map(node):
    """Affine reference->physical map x = v0 + J*(r,s,t), J cols v_{k+1}-v0."""
    v0, v1, v2, v3 = TET
    r, s, t = node
    cols = [
        [v1[i] - v0[i] for i in range(3)],
        [v2[i] - v0[i] for i in range(3)],
        [v3[i] - v0[i] for i in range(3)],
    ]
    return tuple(
        v0[i] + cols[0][i] * r + cols[1][i] * s + cols[2][i] * t
        for i in range(3)
    )


def f64(v) -> str:
    return f"{float(sp.N(v, 30)):.17e}"


def emit_flat(name: str, vals, n: int) -> str:
    entries = ", ".join(f64(v) for v in vals)
    return f"const {name}: [f64; {n}] = [{entries}];\n"


def tet_literal() -> str:
    rows = ", ".join(
        "[" + ", ".join(f64(c) for c in v) + "]" for v in TET
    )
    return f"const TET: [[f64; 3]; 4] = [{rows}];\n"


HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/td_dg/emit_rhs_curl_golden.py — do not edit.
// Golden for the DGTD physical curl operator (rhs.rs, `element_curl`).
//
// A vector field E with degree-<=p polynomial components, sampled at the DG
// nodes of a concrete physical tetrahedron, is fed into the real curl
// operator; the result must equal the EXACT analytic curl(E) sampled at the
// same nodes. The affine map pulls a degree-d physical polynomial back to a
// degree-d reference polynomial, the nodal-DG diff matrices Dr/Ds/Dt are
// exact to degree p, and the constant J^-1 metric converts reference
// derivatives to physical ones with no error — so the operator reproduces
// curl(E) to rounding. Field / output layout is node-major
// `v[node*3 + comp]`, comp = x,y,z, matching rhs.rs.

use rapidfem_td::dg_basis::ReferenceElement;
use rapidfem_td::geom_factors::GeometricFactors;
use rapidfem_td::rhs::element_curl;

/// Max entrywise absolute difference divided by the max magnitude in the
/// golden vector (global relative error).
fn max_rel_err(got: &[f64], want: &[f64]) -> f64 {
    assert_eq!(got.len(), want.len(), "length mismatch");
    let mut num = 0.0_f64;
    let mut scale = 1e-300_f64;
    for (g, w) in got.iter().zip(want.iter()) {
        scale = scale.max(w.abs());
        num = num.max((g - w).abs());
    }
    num / scale
}
"""


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out_path = os.path.join(
        repo, "crates", "rapidfem-td", "tests", "rhs_curl_golden_test.rs"
    )
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    nodes = equispaced_nodes(P)
    n = len(nodes)  # Np
    dof = 3 * n

    field_vals = []
    curl_vals = []
    for nd in nodes:
        px, py, pz = phys_map(nd)
        subs = {x: px, y: py, z: pz}
        for comp in range(3):
            field_vals.append(sp.expand(E[comp].subs(subs)))
        for comp in range(3):
            curl_vals.append(sp.expand(CURL[comp].subs(subs)))

    body = HEADER
    body += f"\n// ===== order p = {P}  (Np = {n}) =====\n"
    body += tet_literal()
    body += emit_flat("FIELD", field_vals, dof)
    body += emit_flat("CURL", curl_vals, dof)
    body += f"""
#[test]
fn rhs_curl_matches_exact_polynomial_curl() {{
    let re = ReferenceElement::new({P});
    assert_eq!(re.n_nodes, {n}, "Np for p={P}");
    let gf = GeometricFactors::for_tet(&TET);
    let got = element_curl(&re, &gf, &FIELD);
    let err = max_rel_err(&got, &CURL);
    eprintln!("rhs curl: max rel err {{:.2e}}", err);
    assert!(err < 1e-9, "curl mismatch: {{:.2e}}", err);
}}
"""
    with open(out_path, "w") as fh:
        fh.write(body)
    print(f"wrote {out_path}  (Np={n}, dof={dof})")


if __name__ == "__main__":
    main()
