// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// This file is part of rapidfem, distributed under GPL-3.0-or-later with
// the Gmsh additional permission. See LICENSE for the full terms.

//! Touchstone S-parameter file export.
//!
//! Implements the public Touchstone File Format (IBIS Open Forum, "Touchstone
//! File Format Specification" rev 1.1/2.0): a `# GHZ S RI R <z0>` option line
//! followed by one record per frequency. The .s2p two-port record is written
//! in the format's column-major order (S11 S21 S12 S22); for N>2 ports the
//! row-major SNP layout with 4 complex values per line is used.

use num_complex::Complex64 as C64;
use std::io::Write;

/// Write S-parameters to a Touchstone file.
///
/// `frequencies`: frequency points in Hz
/// `s_params`: s_params[freq_idx][row][col], complex S-matrix per frequency
/// `n_ports`: number of ports
/// `z0`: reference impedance (default 50Ω)
pub fn write_touchstone(
    path: &str,
    frequencies: &[f64],
    s_params: &[Vec<Vec<C64>>],
    n_ports: usize,
    z0: f64,
) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;

    // Header
    writeln!(file, "! Touchstone file generated by RapidFEM")?;
    writeln!(file, "! Ports: {}", n_ports)?;
    writeln!(file, "# GHZ S RI R {:.0}", z0)?;

    // Data: one line per frequency
    for (fi, &freq) in frequencies.iter().enumerate() {
        let freq_ghz = freq / 1e9;
        write!(file, "{:.6e}", freq_ghz)?;

        // S-parameter ordering. Touchstone .s2p uses column-major order
        // (freq S11 S21 S12 S22); the SNP layout for N>2 is row-major.
        if n_ports <= 2 {
            // .s2p column-major: outer loop over the input port (column),
            // inner over the output port (row). .s1p is order-insensitive.
            for j in 0..n_ports {
                for i in 0..n_ports {
                    let s = s_params[fi][i][j];
                    write!(file, " {:.8e} {:.8e}", s.re, s.im)?;
                }
            }
            writeln!(file)?;
        } else {
            // SNP (N>2): 4 values per line after frequency, then continuation lines
            let mut vals = Vec::new();
            for i in 0..n_ports {
                for j in 0..n_ports {
                    let s = s_params[fi][i][j];
                    vals.push(s.re);
                    vals.push(s.im);
                }
            }
            for (vi, &v) in vals.iter().enumerate() {
                if vi > 0 && vi % 8 == 0 {
                    writeln!(file)?;
                    write!(file, "           ")?;
                }
                write!(file, " {:.8e}", v)?;
            }
            writeln!(file)?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn s2p_writes_column_major_s21_before_s12() {
        // Touchstone .s2p column order is S11 S21 S12 S22. Build a 2-port
        // matrix with a distinct value per entry so a transposed write is
        // detectable, then read the data line back.
        let s = vec![vec![
            vec![C64::new(11.0, 0.0), C64::new(12.0, 0.0)],
            vec![C64::new(21.0, 0.0), C64::new(22.0, 0.0)],
        ]];
        let path = std::env::temp_dir()
            .join(format!("rapidfem_ts_{}.s2p", std::process::id()));
        let path_str = path.to_str().unwrap();
        write_touchstone(path_str, &[1e9], &s, 2, 50.0).unwrap();

        let text = std::fs::read_to_string(path_str).unwrap();
        let data_line = text
            .lines()
            .find(|l| !l.starts_with('!') && !l.starts_with('#'))
            .unwrap();
        let nums: Vec<f64> = data_line
            .split_whitespace()
            .map(|t| t.parse().unwrap())
            .collect();
        // freq, then (re,im) pairs for S11 S21 S12 S22.
        assert_eq!(nums[1], 11.0, "S11");
        assert_eq!(nums[3], 21.0, "S21 must precede S12 in .s2p");
        assert_eq!(nums[5], 12.0, "S12");
        assert_eq!(nums[7], 22.0, "S22");

        let _ = std::fs::remove_file(path_str);
    }
}
