"""Stacked transformer on Sky130, loaded from a rapidpassives JSON export.

Two windings on adjacent top metals (met4 + met5) stacked vertically rather
than side-by-side, generated by ``rapidpassives.StackedTransformer``. Each
turn of the primary sits directly above the matching turn on the secondary,
the geometry is compact (small footprint per nH) at the cost of a
higher primary-secondary capacitance compared to a symmetric trafo.

Four lumped ports come out of the JSON: P+ / P- on the primary, S+ / S-
on the secondary. The S-matrix below shows the primary↔secondary mutual
coupling, |S31| / |S42| pick up the magnetic coupling between the
stacked windings.
"""

# %% Load + build the geometry from JSON
from importlib.resources import files
from pathlib import Path

import numpy as np

import rapidfem as rf
import rapidfem.rfic as rfic

JSON_PATH = Path(str(files("rapidfem.examples")
                     / "fd_rfic_stacked_transformer_from_json.fem.json"))

layout = rfic.from_fem_json(JSON_PATH)

print(f"loaded {layout.doc['metadata']['generator']} layout")
print(f"  params: {layout.doc['metadata']['params']}")
print(f"  conductors:")
for layer_id, vols in layout.conductors.items():
    print(f"    {layer_id}: {len(vols)} volume(s)")
print(f"  ports: {list(layout.ports)}")

rf.show(layout.geometry)


# %% Mesh (the bridge placed the physics: PEC conductor
# walls, 50 Ohm lumped ports, ABC outside)
layout.geometry.mesh()
rf.show(layout.geometry)


# %% Sweep
FREQS_HZ = np.linspace(1e9, 30e9, 12)

prob = rf.ProblemFD(layout.geometry)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% S-matrix magnitude table, primary↔secondary coupling
port_names = list(layout.ports)
n = len(port_names)

print(f"\nDOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"ports order: {port_names}")
for fi, f in enumerate(FREQS_HZ):
    S = result.sparams[fi]
    print(f"\n  f = {f * 1e-9:.1f} GHz")
    header = "       " + "  ".join(f"{nm:>6s}" for nm in port_names)
    print(header)
    for i in range(n):
        row = f"  {port_names[i]:>4s} " + "  ".join(
            f"{abs(S[i, j]):>6.3f}" for j in range(n)
        )
        print(row)
