"""Symmetric inductor on Sky130, loaded from a rapidpassives JSON export.

Differential 4-turn symmetric inductor (Dout = 250 µm, width = 8 µm,
spacing = 2 µm) generated by ``rapidpassives.SymmetricInductor`` and
shipped here as the bundled ``fd_rfic_symmetric_inductor_from_json.fem.json``.

Topologically richer than the spiral: each turn alternates between the
two outer windings on met5 with crossings on met4, joined by 6 merged
via arrays where the windings hand off. The export includes a guard
ring on met5 + met4 (as 4 separate strips after the merge fallback for
frame shapes).

Series-mode inductance is extracted the same way as the spiral example,
``L_series = Im(Z11 - Z21) / ω`` de-embeds the port-plate shunt cap so
the residual is the differential-mode inductance of the winding.
"""

# %% Load + build the geometry from JSON
import math
from importlib.resources import files
from pathlib import Path

import numpy as np

import rapidfem as rf
import rapidfem.rfic as rfic

JSON_PATH = Path(str(files("rapidfem.examples")
                     / "fd_rfic_symmetric_inductor_from_json.fem.json"))

layout = rfic.from_fem_json(JSON_PATH)

print(f"loaded {layout.doc['metadata']['generator']} layout")
print(f"  params: {layout.doc['metadata']['params']}")
print(f"  conductors:")
for layer_id, vols in layout.conductors.items():
    print(f"    {layer_id}: {len(vols)} volume(s)")
print(f"  ports: {list(layout.ports)}")

rf.show(layout.geometry)


# %% Mesh (the bridge placed the physics: PEC conductor
# walls, 50 Ohm lumped ports, ABC outside)
layout.geometry.mesh()
rf.show(layout.geometry)


# %% Sweep across the RF band
FREQS_HZ = np.linspace(1e9, 30e9, 16)

prob = rf.ProblemFD(layout.geometry)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% Differential-mode L extraction
n_ports = len(layout.ports)
I = np.eye(n_ports)
z0 = 50.0

print(f"\nDOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"{'f [GHz]':>9} {'L [nH]':>9} {'|S21|':>7}")
for i, f in enumerate(FREQS_HZ):
    S = result.sparams[i]
    Z = math.sqrt(z0) * (I + S) @ np.linalg.inv(I - S) * math.sqrt(z0)
    omega = 2 * math.pi * f
    L_series = (Z[0, 0].imag - Z[1, 0].imag) / omega
    print(f"{f * 1e-9:>9.1f} {L_series * 1e9:>9.3f} {abs(S[1, 0]):>7.3f}")
