"""Symmetric transformer on Sky130, loaded from a rapidpassives JSON export.

A 2:4 differential symmetric transformer (Dout = 350 µm) with a primary
center tap, generated by ``rapidpassives.SymmetricTransformer``. Five
lumped ports come out of the JSON: P1+ / P1- on the primary, P2+ / P2-
on the secondary, and CT1 in the middle of the primary winding.

.. warning::

   The rapidpassives ``symmetric_transformer`` generator currently emits
   the winding metal polygons but no via polygons for this config, see
   the known-issue task in the project tracker. As a result the windings
   and crossings stay electrically disconnected here; primary↔secondary
   coupling you see in the S-matrix below is only free-space mutual
   inductance, NOT the conductive routing of a real layout. The geometry
   still exercises the FEM bridge end-to-end (5 ports, 55 conductor
   volumes, ~650k DOFs); the numbers themselves wait on the generator
   fix.
"""

# %% Load + build the geometry from JSON
import math
from importlib.resources import files
from pathlib import Path

import numpy as np

import rapidfem as rf
import rapidfem.rfic as rfic

JSON_PATH = Path(str(files("rapidfem.examples")
                     / "fd_rfic_symmetric_transformer_from_json.fem.json"))

layout = rfic.from_fem_json(JSON_PATH)

print(f"loaded {layout.doc['metadata']['generator']} layout")
print(f"  params: {layout.doc['metadata']['params']}")
print(f"  conductors:")
for layer_id, vols in layout.conductors.items():
    print(f"    {layer_id}: {len(vols)} volume(s)")
print(f"  ports: {list(layout.ports)}")

rf.show(layout.geometry)


# %% Mesh (the bridge placed the physics: PEC conductor
# walls, 50 Ohm lumped ports, ABC outside)
layout.geometry.mesh()
rf.show(layout.geometry)


# %% Sweep, keep it short, this geometry is heavy
FREQS_HZ = np.linspace(1e9, 30e9, 12)

prob = rf.ProblemFD(layout.geometry)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% S-matrix magnitude table, quick look at primary↔secondary coupling
port_names = list(layout.ports)
n = len(port_names)

print(f"\nDOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"ports order: {port_names}")
for fi, f in enumerate(FREQS_HZ):
    S = result.sparams[fi]
    print(f"\n  f = {f * 1e-9:.1f} GHz")
    header = "       " + "  ".join(f"{nm:>6s}" for nm in port_names)
    print(header)
    for i in range(n):
        row = f"  {port_names[i]:>4s} " + "  ".join(
            f"{abs(S[i, j]):>6.3f}" for j in range(n)
        )
        print(row)
