"""Rat-race (180° hybrid) coupler on Sky130, loaded from a rapidpassives JSON export.

A ring-shaped 4-port hybrid generated by ``rapidpassives.RatraceCoupler``.
Three branches are λ/4 long and the fourth is 3λ/4, giving the canonical
sum / difference behaviour: feeding port 1 puts a sum at port 2 and
a difference at port 4 (port 3 isolated), and vice-versa for port 3.

The geometry hits the polygon-with-holes pipeline in rapidfem, the ring
is exported as a single annular polygon whose inner boundary is a hole,
and the FEM bridge keeps the hole in the extruded prism, so the inside
of the ring stays oxide, not metal.

At the chosen 10 GHz operating point the on-chip ring is too small for
the design wavelength (this PDK + dimensions land deep below the
intended band), the four-port S-matrix below mainly demonstrates that
the coupler topology / port connectivity is alive, rather than a usable
hybrid response.
"""

# %% Load + build the geometry from JSON
from importlib.resources import files
from pathlib import Path

import numpy as np

import rapidfem as rf
import rapidfem.rfic as rfic

JSON_PATH = Path(str(files("rapidfem.examples")
                     / "fd_rfic_ratrace_coupler_from_json.fem.json"))

layout = rfic.from_fem_json(JSON_PATH)

print(f"loaded {layout.doc['metadata']['generator']} layout")
print(f"  params: {layout.doc['metadata']['params']}")
print(f"  conductors:")
for layer_id, vols in layout.conductors.items():
    print(f"    {layer_id}: {len(vols)} volume(s)")
print(f"  ports: {list(layout.ports)}")

rf.show(layout.geometry)


# %% Mesh (the bridge placed the physics: PEC conductor
# walls, 50 Ohm lumped ports, ABC outside)
# The ring spans 300 um: twice the default sizes keep it to ~130k tets, within
# 0.004 in |S| of 1.5 times them (a mesh study).
layout.geometry.size_scale = 2.0
layout.geometry.mesh()
rf.show(layout.geometry)


# %% Sweep
FREQS_HZ = np.linspace(2e9, 30e9, 12)

prob = rf.ProblemFD(layout.geometry)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% 4×4 S-matrix magnitude, sum / difference behaviour
port_names = list(layout.ports)
n = len(port_names)

print(f"\nDOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"ports order: {port_names}")
for fi, f in enumerate(FREQS_HZ):
    S = result.sparams[fi]
    print(f"\n  f = {f * 1e-9:.1f} GHz")
    header = "       " + "  ".join(f"{nm:>6s}" for nm in port_names)
    print(header)
    for i in range(n):
        row = f"  {port_names[i]:>4s} " + "  ".join(
            f"{abs(S[i, j]):>6.3f}" for j in range(n)
        )
        print(row)
