"""Spiral inductor loaded from a rapidpassives FEM-JSON export.

End-to-end demo of the ``rapidpassives → rapidfem`` pipeline: pull a
parametric layout out of the rapidpassives web app via the "Export FEM
JSON" button, hand the file to :func:`rapidfem.rfic.from_fem_json`, and
get a ready-to-mesh 3-D geometry with extruded conductors, vias, and
port plates.

The bundled JSON ``fd_rfic_spiral_from_json.fem.json`` is a 3-turn
octagonal spiral on the SKY130 stack (Dout = 130 µm, width = 10 µm,
spacing = 4 µm) generated by ``rapidpassives.SpiralInductor``. Every
metal piece, windings on met5, crossings on met4, the merged via on
via4, is extruded to its real PDK thickness, so the result is
honest at >10 GHz where the skin depth drops below the metal height.

Series inductance is extracted from the 2-port Z matrix as
``L = Im(Z11 - Z21) / ω``, the standard de-embedding for a structure
whose port-plate shunt capacitance dominates Z11 ≈ Z21.
"""

# %% Load + build the geometry from JSON
import math
from importlib.resources import files
from pathlib import Path

import numpy as np

import rapidfem as rf
import rapidfem.rfic as rfic

# Resolve relative to the installed examples package so this works inside the
# wheel, inside the bake-demo runner (which leaves __file__ bare), and from a
# checked-out source tree alike.
JSON_PATH = Path(str(files("rapidfem.examples") / "fd_rfic_spiral_from_json.fem.json"))

layout = rfic.from_fem_json(JSON_PATH)

print(f"loaded {layout.doc['metadata']['generator']} layout")
print(f"  params: {layout.doc['metadata']['params']}")
print(f"  conductors:")
for layer_id, vols in layout.conductors.items():
    print(f"    {layer_id}: {len(vols)} volume(s)")
print(f"  ports: {list(layout.ports)}")

rf.show(layout.geometry)


# %% Mesh (the bridge placed the physics: PEC conductor
# walls, 50 Ohm lumped ports, ABC outside)
layout.geometry.mesh()
rf.show(layout.geometry)


# %% Sweep across the RF band
FREQS_HZ = np.linspace(1e9, 50e9, 20)

prob = rf.ProblemFD(layout.geometry)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% Series-L extraction (de-embedded from common-mode shunt)
n_ports = len(layout.ports)
I = np.eye(n_ports)
z0 = 50.0

print(f"\nDOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"{'f [GHz]':>9} {'L [nH]':>9} {'|S21|':>7}")
for i, f in enumerate(FREQS_HZ):
    S = result.sparams[i]
    Z = math.sqrt(z0) * (I + S) @ np.linalg.inv(I - S) * math.sqrt(z0)
    omega = 2 * math.pi * f
    L_series = (Z[0, 0].imag - Z[1, 0].imag) / omega
    print(f"{f * 1e-9:>9.1f} {L_series * 1e9:>9.3f} {abs(S[1, 0]):>7.3f}")
