# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for coefficients.rs from the sympy derivation.

Writes crates/rapidfem-fd/tests/coefficients_golden_test.rs with the full
volume/area coefficient tables as exact f64 values, so `cargo test` proves
the hand-written Rust formula reproduces the independently derived numbers.
"""
from __future__ import annotations

import os

from barycentric import derive_and_verify

HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/nedelec2/emit_coefficients_test.py — do not edit.
// Golden values are the exact rationals derived from scratch by symbolic
// integration over the reference simplex (barycentric.py), evaluated as f64.
// This pins coefficients.rs to an independent derivation of the integration
// identity, not to any third-party source.

use rapidfem_fd::coefficients::{area_coeff, volume_coeff};

"""


def fmt_table(name, table):
    lines = [f"const {name}: &[(usize, usize, usize, usize, f64)] = &["]
    for (a, b, c, d), v in sorted(table.items()):
        lines.append(f"    ({a}, {b}, {c}, {d}, {float(v):.17e}),")
    lines.append("];")
    return "\n".join(lines)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out_path = os.path.join(
        repo, "crates", "rapidfem-fd", "tests", "coefficients_golden_test.rs"
    )
    vol_table, area_table = derive_and_verify()

    body = HEADER
    body += fmt_table("VOLUME_GOLDEN", vol_table) + "\n\n"
    body += fmt_table("AREA_GOLDEN", area_table) + "\n\n"
    body += """\
#[test]
fn volume_coeff_matches_symbolic_derivation() {
    let mut max_err = 0.0_f64;
    for &(a, b, c, d, want) in VOLUME_GOLDEN {
        let got = volume_coeff(a, b, c, d);
        let err = (got - want).abs() / want.abs().max(1e-300);
        max_err = max_err.max(err);
        assert!(err < 1e-14, "volume_coeff({a},{b},{c},{d}) = {got:e}, want {want:e}");
    }
    eprintln!("volume_coeff: {} golden values, max rel err {:.2e}", VOLUME_GOLDEN.len(), max_err);
}

#[test]
fn area_coeff_matches_symbolic_derivation() {
    let mut max_err = 0.0_f64;
    for &(a, b, c, d, want) in AREA_GOLDEN {
        let got = area_coeff(a, b, c, d);
        let err = (got - want).abs() / want.abs().max(1e-300);
        max_err = max_err.max(err);
        assert!(err < 1e-14, "area_coeff({a},{b},{c},{d}) = {got:e}, want {want:e}");
    }
    eprintln!("area_coeff: {} golden values, max rel err {:.2e}", AREA_GOLDEN.len(), max_err);
}
"""
    with open(out_path, "w") as f:
        f.write(body)
    print(f"wrote {out_path}")
    print(f"  {len(vol_table)} volume + {len(area_table)} area golden values")


if __name__ == "__main__":
    main()
