# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for tet_assembly_r2.rs from the sympy element.

Generates full 20×20 D and F matrices for several tets and material tensors
(symbolic, exact integration) and writes a cargo test that asserts the
clean-room Rust assembler reproduces them entrywise.
"""
from __future__ import annotations

import os

import sympy as sp

import element

I = sp.I

# Local maps used by element.py (must match the Rust test).
EDGE_MAP = element.LOCAL_EDGE_MAP
TRI_MAP = element.LOCAL_TRI_MAP


def edge_lengths(verts):
    return [element.dist(verts, a, b) for (a, b) in EDGE_MAP]


# (name, verts, eps 3x3, mu_inv 3x3)
CASES = [
    (
        "unit_identity",
        [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)],
        sp.eye(3),
        sp.eye(3),
    ),
    (
        "skew_identity",
        [(0, 0, 0), (2, 0, 0), (sp.Rational(1, 2), 1, 0), (sp.Rational(1, 3), sp.Rational(1, 4), 1)],
        sp.eye(3),
        sp.eye(3),
    ),
    (
        "skew_aniso_complex",
        [(0, 0, 0), (2, 0, 0), (sp.Rational(1, 2), 1, 0), (sp.Rational(1, 3), sp.Rational(1, 4), 1)],
        sp.diag(2 - I / 10, 3, 4 + I / 5),
        sp.diag(1, sp.Rational(6, 5), sp.Rational(4, 5) - I / 20),
    ),
]


def c64(z):
    z = complex(sp.N(z, 20))
    return f"C64::new({z.real:.17e}, {z.imag:.17e})"


def f64(v):
    return f"{float(sp.N(v, 20)):.17e}"


def emit_matrix(name, M):
    rows = []
    for i in range(20):
        entries = ", ".join(c64(M[i, j]) for j in range(20))
        rows.append(f"    [{entries}],")
    body = "\n".join(rows)
    return f"const {name}: [[C64; 20]; 20] = [\n{body}\n];\n"


def emit_tensor(name, T):
    rows = []
    for i in range(3):
        entries = ", ".join(c64(T[i, j]) for j in range(3))
        rows.append(f"    [{entries}],")
    body = "\n".join(rows)
    return f"const {name}: [[C64; 3]; 3] = [\n{body}\n];\n"


def emit_arr(name, vals, fmt):
    body = ", ".join(fmt(v) for v in vals)
    return f"const {name}: [f64; {len(vals)}] = [{body}];\n"


HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/nedelec2/emit_element_golden.py — do not edit.
// Golden 20×20 D (stiffness) and F (mass) matrices from the independent
// symbolic R2 element (element.py), exact integration. Pins the clean-room
// Rust assembler to the derivation, entrywise.

use num_complex::Complex64 as C64;
use rapidfem_fd::tet_assembly_r2::r2_tet_stiff_mass;

const EDGE_MAP: [[usize; 2]; 6] = [[0,1],[0,2],[0,3],[1,2],[3,1],[2,3]];
const TRI_MAP: [[usize; 3]; 4] = [[0,1,2],[0,2,3],[0,3,1],[1,2,3]];

fn maxdiff(a: &[[C64; 20]; 20], b: &[[C64; 20]; 20]) -> f64 {
    let mut m = 0.0_f64;
    let mut scale = 1e-300_f64;
    for i in 0..20 { for j in 0..20 {
        scale = scale.max(b[i][j].norm());
        m = m.max((a[i][j] - b[i][j]).norm());
    }}
    m / scale
}
"""


def emit_case(name, verts, eps, mu_inv):
    D, F = element.element_matrices(verts, eps, mu_inv)
    xs = [v[0] for v in verts]
    ys = [v[1] for v in verts]
    zs = [v[2] for v in verts]
    el = edge_lengths(verts)
    out = f"\n// ===== case {name} =====\n"
    out += emit_arr(f"XS_{name}", xs, f64)
    out += emit_arr(f"YS_{name}", ys, f64)
    out += emit_arr(f"ZS_{name}", zs, f64)
    out += emit_arr(f"EL_{name}", el, f64)
    out += emit_tensor(f"EPS_{name}", eps)
    out += emit_tensor(f"MUINV_{name}", mu_inv)
    out += emit_matrix(f"D_{name}", D)
    out += emit_matrix(f"F_{name}", F)
    out += f"""
#[test]
fn r2_element_matches_derivation_{name}() {{
    let (d, f) = r2_tet_stiff_mass(&XS_{name}, &YS_{name}, &ZS_{name}, &EL_{name},
        &EDGE_MAP, &TRI_MAP, &MUINV_{name}, &EPS_{name});
    let derr = maxdiff(&d, &D_{name});
    let ferr = maxdiff(&f, &F_{name});
    eprintln!("{name}: max rel D err {{:.2e}}, F err {{:.2e}}", derr, ferr);
    assert!(derr < 1e-12, "D mismatch ({name}): {{:.2e}}", derr);
    assert!(ferr < 1e-12, "F mismatch ({name}): {{:.2e}}", ferr);
}}
"""
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out_path = os.path.join(repo, "crates", "rapidfem-fd", "tests", "r2_element_golden_test.rs")
    body = HEADER
    for name, verts, eps, mu in CASES:
        body += emit_case(name, verts, eps, mu)
        print(f"emitted case {name}")
    with open(out_path, "w") as fh:
        fh.write(body)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
