// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/materials/emit_debye_golden.py — do not edit.
// Golden complex relative permittivity for the Debye dispersion model.
// Pins rapidfem_core::materials::Dispersion::Debye::evaluate to the exact
// closed form  ε(ω) = ε∞ + (εs - ε∞)/(1 + jωτ),  ω = 2π f  (e^{+jωt}).

use rapidfem_core::materials::Dispersion;

fn rel_err(got: f64, want: f64) -> f64 {
    let scale = want.abs().max(1e-300);
    (got - want).abs() / scale
}

// ===== case water_like: er_inf=4.9, er_static=78.4, tau_s=8.27e-12 =====
#[test]
fn debye_matches_closed_form_water_like() {
    let disp = Dispersion::Debye {
        er_inf: 4.90000000000000036e+00,
        er_static: 7.84000000000000057e+01,
        tau_s: 8.26999999999999929e-12,
    };
    // (frequency_hz, want_re, want_im)
    let table: &[(f64, f64, f64)] = &[
        (1.00000000000000000e+06, 7.83999998015468123e+01, -3.81920276273056214e-03),
        (1.00000000000000000e+09, 7.82020811945258743e+01, -3.80891852745476500e+00),
        (2.40000000000000000e+09, 7.72744149777342670e+01, -9.02571645323418181e+00),
        (6.00000000000000000e+10, 1.17562432012713067e+01, -2.13758228954691241e+01),
        (3.00000000000000000e+11, 5.20122467864715876e+00, -4.69566582856362125e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(freq, want_re, want_im) in table {
        // base_er is unused by the Debye branch; pass a dummy value.
        let z = disp.evaluate(1.0, freq);
        let er = rel_err(z.re, want_re);
        let ei = rel_err(z.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "water_like re mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.re, want_re, er);
        assert!(ei < 1e-12, "water_like im mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.im, want_im, ei);
    }
    eprintln!("water_like: max rel err {:.2e}", max_err);
}

// ===== case low_loss: er_inf=2.1, er_static=2.1, tau_s=1e-09 =====
#[test]
fn debye_matches_closed_form_low_loss() {
    let disp = Dispersion::Debye {
        er_inf: 2.10000000000000009e+00,
        er_static: 2.10000000000000009e+00,
        tau_s: 1.00000000000000006e-09,
    };
    // (frequency_hz, want_re, want_im)
    let table: &[(f64, f64, f64)] = &[
        (1.00000000000000000e+06, 2.10000000000000009e+00, 0.00000000000000000e+00),
        (1.00000000000000000e+09, 2.10000000000000009e+00, 0.00000000000000000e+00),
        (2.40000000000000000e+09, 2.10000000000000009e+00, 0.00000000000000000e+00),
        (6.00000000000000000e+10, 2.10000000000000009e+00, 0.00000000000000000e+00),
        (3.00000000000000000e+11, 2.10000000000000009e+00, 0.00000000000000000e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(freq, want_re, want_im) in table {
        // base_er is unused by the Debye branch; pass a dummy value.
        let z = disp.evaluate(1.0, freq);
        let er = rel_err(z.re, want_re);
        let ei = rel_err(z.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "low_loss re mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.re, want_re, er);
        assert!(ei < 1e-12, "low_loss im mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.im, want_im, ei);
    }
    eprintln!("low_loss: max rel err {:.2e}", max_err);
}

// ===== case high_contrast: er_inf=1.0, er_static=100.0, tau_s=1e-06 =====
#[test]
fn debye_matches_closed_form_high_contrast() {
    let disp = Dispersion::Debye {
        er_inf: 1.00000000000000000e+00,
        er_static: 1.00000000000000000e+02,
        tau_s: 9.99999999999999955e-07,
    };
    // (frequency_hz, want_re, want_im)
    let table: &[(f64, f64, f64)] = &[
        (1.00000000000000000e+06, 3.44574778015390670e+00, -1.53670865173301152e+01),
        (1.00000000000000000e+09, 1.00000250769923160e+00, -1.57563389669849105e-02),
        (2.40000000000000000e+09, 1.00000043536445915e+00, -6.56514137366968030e-03),
        (6.00000000000000000e+10, 1.00000000069658324e+00, -2.62605656099779551e-04),
        (3.00000000000000000e+11, 1.00000000002786327e+00, -5.25211312203106802e-05),
    ];
    let mut max_err = 0.0_f64;
    for &(freq, want_re, want_im) in table {
        // base_er is unused by the Debye branch; pass a dummy value.
        let z = disp.evaluate(1.0, freq);
        let er = rel_err(z.re, want_re);
        let ei = rel_err(z.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "high_contrast re mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.re, want_re, er);
        assert!(ei < 1e-12, "high_contrast im mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.im, want_im, ei);
    }
    eprintln!("high_contrast: max rel err {:.2e}", max_err);
}

// ===== case negative_drop: er_inf=12.0, er_static=3.0, tau_s=2.5e-10 =====
#[test]
fn debye_matches_closed_form_negative_drop() {
    let disp = Dispersion::Debye {
        er_inf: 1.20000000000000000e+01,
        er_static: 3.00000000000000000e+00,
        tau_s: 2.50000000000000016e-10,
    };
    // (frequency_hz, want_re, want_im)
    let table: &[(f64, f64, f64)] = &[
        (1.00000000000000000e+06, 3.00002220655510987e+00, 1.41371320591788738e-02),
        (1.00000000000000000e+09, 9.40439604772199189e+00, 4.07716515405261148e+00),
        (2.40000000000000000e+09, 1.14083707779671677e+01, 2.23038962110486727e+00),
        (6.00000000000000000e+10, 1.19989869022172062e+01, 9.54822165538060513e-02),
        (3.00000000000000000e+11, 1.19999594717090492e+01, 1.90985071673229062e-02),
    ];
    let mut max_err = 0.0_f64;
    for &(freq, want_re, want_im) in table {
        // base_er is unused by the Debye branch; pass a dummy value.
        let z = disp.evaluate(1.0, freq);
        let er = rel_err(z.re, want_re);
        let ei = rel_err(z.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "negative_drop re mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.re, want_re, er);
        assert!(ei < 1e-12, "negative_drop im mismatch @ {:.3e} Hz: got {:.17e} want {:.17e} (rel {:.2e})", freq, z.im, want_im, ei);
    }
    eprintln!("negative_drop: max rel err {:.2e}", max_err);
}
