// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/materials/emit_material_golden.py — do not edit.
// Golden material tensors for the frequency-domain assembly.
//   (A) Uniaxial PML stretch  s_d = 1 - j·(u^n·δmax),  u = max(0, sign·(coord-inner)/t)
//   (B) Lossy dielectric      εr* = εr·(1 - j·tanδ) - j·σ/(ω·ε₀)
// Both pinned to the exact closed forms the Rust implements (e^{+jωt}).

use rapidfem_core::materials::{build_material_tensors, Dispersion, Material, PmlRegion};

fn rel_err(got: f64, want: f64) -> f64 {
    let scale = want.abs().max(1e-300);
    (got - want).abs() / scale
}

// ===== PML plus_x: dir=[1.0, 0.0, 0.0], inner=0.04, t=0.01, n=2.0, dmax=8.0 =====
#[test]
fn pml_stretch_matches_closed_form_plus_x() {
    let region = PmlRegion {
        tet_indices: vec![],
        er_base: 1.0,
        ur_base: 1.0,
        direction: [1.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00],
        inner_face: 4.00000000000000008e-02,
        thickness: 1.00000000000000002e-02,
        exponent: 2.00000000000000000e+00,
        delta_max: 8.00000000000000000e+00,
    };
    // (x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im)
    let table: &[(f64, f64, f64, f64, f64, f64, f64, f64, f64)] = &[
        (2.99999999999999989e-02, 5.00000000000000000e-01, -2.99999999999999989e-01, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (4.00000000000000008e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (4.25000000000000031e-02, 1.00000000000000000e+00, 2.00000000000000000e+00, 1.00000000000000000e+00, -5.00000000000000888e-01, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (4.49999999999999983e-02, -1.00000000000000000e+00, 5.00000000000000000e-01, 1.00000000000000000e+00, -1.99999999999999778e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (5.00000000000000028e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -8.00000000000000355e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (5.50000000000000003e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -1.80000000000000000e+01, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im) in table {
        let s = region.stretch(x, y, z);
        let want = [(sx_re, sx_im), (sy_re, sy_im), (sz_re, sz_im)];
        for k in 0..3 {
            let er = rel_err(s[k].re, want[k].0);
            let ei = rel_err(s[k].im, want[k].1);
            max_err = max_err.max(er).max(ei);
            assert!(er < 1e-12, "plus_x s[{}] re mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].re, want[k].0, er);
            assert!(ei < 1e-12, "plus_x s[{}] im mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].im, want[k].1, ei);
        }
    }
    eprintln!("pml plus_x: max rel err {:.2e}", max_err);
}

// ===== PML minus_z: dir=[0.0, 0.0, -1.0], inner=-0.02, t=0.008, n=3.0, dmax=6.0 =====
#[test]
fn pml_stretch_matches_closed_form_minus_z() {
    let region = PmlRegion {
        tet_indices: vec![],
        er_base: 1.0,
        ur_base: 1.0,
        direction: [0.00000000000000000e+00, 0.00000000000000000e+00, -1.00000000000000000e+00],
        inner_face: -2.00000000000000004e-02,
        thickness: 8.00000000000000017e-03,
        exponent: 3.00000000000000000e+00,
        delta_max: 6.00000000000000000e+00,
    };
    // (x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im)
    let table: &[(f64, f64, f64, f64, f64, f64, f64, f64, f64)] = &[
        (1.00000000000000006e-01, 2.00000000000000011e-01, -1.00000000000000002e-02, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (0.00000000000000000e+00, 0.00000000000000000e+00, -2.00000000000000004e-02, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (1.00000000000000000e+00, -1.00000000000000000e+00, -2.19999999999999987e-02, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -9.37499999999997502e-02),
        (0.00000000000000000e+00, 0.00000000000000000e+00, -2.59999999999999988e-02, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -2.53124999999999778e+00),
        (0.00000000000000000e+00, 0.00000000000000000e+00, -2.80000000000000006e-02, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -6.00000000000000000e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im) in table {
        let s = region.stretch(x, y, z);
        let want = [(sx_re, sx_im), (sy_re, sy_im), (sz_re, sz_im)];
        for k in 0..3 {
            let er = rel_err(s[k].re, want[k].0);
            let ei = rel_err(s[k].im, want[k].1);
            max_err = max_err.max(er).max(ei);
            assert!(er < 1e-12, "minus_z s[{}] re mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].re, want[k].0, er);
            assert!(ei < 1e-12, "minus_z s[{}] im mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].im, want[k].1, ei);
        }
    }
    eprintln!("pml minus_z: max rel err {:.2e}", max_err);
}

// ===== PML plus_y: dir=[0.0, 1.0, 0.0], inner=0.0, t=0.005, n=1.5, dmax=10.0 =====
#[test]
fn pml_stretch_matches_closed_form_plus_y() {
    let region = PmlRegion {
        tet_indices: vec![],
        er_base: 1.0,
        ur_base: 1.0,
        direction: [0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00],
        inner_face: 0.00000000000000000e+00,
        thickness: 5.00000000000000010e-03,
        exponent: 1.50000000000000000e+00,
        delta_max: 1.00000000000000000e+01,
    };
    // (x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im)
    let table: &[(f64, f64, f64, f64, f64, f64, f64, f64, f64)] = &[
        (2.99999999999999989e-01, -1.00000000000000002e-03, 6.99999999999999956e-01, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (-1.00000000000000000e+00, 1.00000000000000002e-03, 2.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -8.94427190999915966e-01, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (0.00000000000000000e+00, 2.50000000000000005e-03, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -3.53553390593273775e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (0.00000000000000000e+00, 5.00000000000000010e-03, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -1.00000000000000000e+01, 1.00000000000000000e+00, 0.00000000000000000e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im) in table {
        let s = region.stretch(x, y, z);
        let want = [(sx_re, sx_im), (sy_re, sy_im), (sz_re, sz_im)];
        for k in 0..3 {
            let er = rel_err(s[k].re, want[k].0);
            let ei = rel_err(s[k].im, want[k].1);
            max_err = max_err.max(er).max(ei);
            assert!(er < 1e-12, "plus_y s[{}] re mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].re, want[k].0, er);
            assert!(ei < 1e-12, "plus_y s[{}] im mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].im, want[k].1, ei);
        }
    }
    eprintln!("pml plus_y: max rel err {:.2e}", max_err);
}

// ===== PML minus_x: dir=[-1.0, 0.0, 0.0], inner=-0.015, t=0.006, n=2.5, dmax=7.5 =====
#[test]
fn pml_stretch_matches_closed_form_minus_x() {
    let region = PmlRegion {
        tet_indices: vec![],
        er_base: 1.0,
        ur_base: 1.0,
        direction: [-1.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00],
        inner_face: -1.49999999999999994e-02,
        thickness: 6.00000000000000012e-03,
        exponent: 2.50000000000000000e+00,
        delta_max: 7.50000000000000000e+00,
    };
    // (x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im)
    let table: &[(f64, f64, f64, f64, f64, f64, f64, f64, f64)] = &[
        (-1.00000000000000002e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (-1.49999999999999994e-02, 1.00000000000000000e+00, -1.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (-1.79999999999999986e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -1.32582521472477555e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
        (-2.10000000000000013e-02, 0.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, -7.50000000000000533e+00, 1.00000000000000000e+00, 0.00000000000000000e+00, 1.00000000000000000e+00, 0.00000000000000000e+00),
    ];
    let mut max_err = 0.0_f64;
    for &(x, y, z, sx_re, sx_im, sy_re, sy_im, sz_re, sz_im) in table {
        let s = region.stretch(x, y, z);
        let want = [(sx_re, sx_im), (sy_re, sy_im), (sz_re, sz_im)];
        for k in 0..3 {
            let er = rel_err(s[k].re, want[k].0);
            let ei = rel_err(s[k].im, want[k].1);
            max_err = max_err.max(er).max(ei);
            assert!(er < 1e-12, "minus_x s[{}] re mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].re, want[k].0, er);
            assert!(ei < 1e-12, "minus_x s[{}] im mismatch @ ({:.4e},{:.4e},{:.4e}): got {:.17e} want {:.17e} (rel {:.2e})", k, x, y, z, s[k].im, want[k].1, ei);
        }
    }
    eprintln!("pml minus_x: max rel err {:.2e}", max_err);
}

// ===== dielectric fr4: er=4.4, tand=0.02, sigma=0.0, f=2400000000.0 =====
#[test]
fn lossy_dielectric_matches_closed_form_fr4() {
    let mat = Material {
        er: 4.40000000000000036e+00,
        ur: 1.0,
        tand: 2.00000000000000004e-02,
        cond: 0.00000000000000000e+00,
        tet_indices: vec![0],
        er_diag: None,
        ur_diag: None,
        dispersion: Dispersion::None,
    };
    let (er_t, _ur_t) = build_material_tensors(1, &[mat], 2.40000000000000000e+09);
    let want_re = 4.40000000000000036e+00;
    let want_im = -8.80000000000000088e-02;
    let mut max_err = 0.0_f64;
    // Isotropic: all three diagonal entries carry the same complex εr*.
    for k in 0..3 {
        let v = er_t[0][k][k];
        let er = rel_err(v.re, want_re);
        let ei = rel_err(v.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "fr4 εr* re mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.re, want_re, er);
        assert!(ei < 1e-12, "fr4 εr* im mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.im, want_im, ei);
    }
    eprintln!("dielectric fr4: max rel err {:.2e}", max_err);
}

// ===== dielectric seawater: er=81.0, tand=0.0, sigma=4.0, f=1000000000.0 =====
#[test]
fn lossy_dielectric_matches_closed_form_seawater() {
    let mat = Material {
        er: 8.10000000000000000e+01,
        ur: 1.0,
        tand: 0.00000000000000000e+00,
        cond: 4.00000000000000000e+00,
        tet_indices: vec![0],
        er_diag: None,
        ur_diag: None,
        dispersion: Dispersion::None,
    };
    let (er_t, _ur_t) = build_material_tensors(1, &[mat], 1.00000000000000000e+09);
    let want_re = 8.10000000000000000e+01;
    let want_im = -7.19004142892527085e+01;
    let mut max_err = 0.0_f64;
    // Isotropic: all three diagonal entries carry the same complex εr*.
    for k in 0..3 {
        let v = er_t[0][k][k];
        let er = rel_err(v.re, want_re);
        let ei = rel_err(v.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "seawater εr* re mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.re, want_re, er);
        assert!(ei < 1e-12, "seawater εr* im mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.im, want_im, ei);
    }
    eprintln!("dielectric seawater: max rel err {:.2e}", max_err);
}

// ===== dielectric lossy_combo: er=10.2, tand=0.0035, sigma=0.01, f=6000000000.0 =====
#[test]
fn lossy_dielectric_matches_closed_form_lossy_combo() {
    let mat = Material {
        er: 1.01999999999999993e+01,
        ur: 1.0,
        tand: 3.50000000000000007e-03,
        cond: 1.00000000000000002e-02,
        tet_indices: vec![0],
        er_diag: None,
        ur_diag: None,
        dispersion: Dispersion::None,
    };
    let (er_t, _ur_t) = build_material_tensors(1, &[mat], 6.00000000000000000e+09);
    let want_re = 1.01999999999999993e+01;
    let want_im = -6.56585059538552923e-02;
    let mut max_err = 0.0_f64;
    // Isotropic: all three diagonal entries carry the same complex εr*.
    for k in 0..3 {
        let v = er_t[0][k][k];
        let er = rel_err(v.re, want_re);
        let ei = rel_err(v.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "lossy_combo εr* re mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.re, want_re, er);
        assert!(ei < 1e-12, "lossy_combo εr* im mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.im, want_im, ei);
    }
    eprintln!("dielectric lossy_combo: max rel err {:.2e}", max_err);
}

// ===== dielectric air: er=1.0, tand=0.0, sigma=0.0, f=10000000000.0 =====
#[test]
fn lossy_dielectric_matches_closed_form_air() {
    let mat = Material {
        er: 1.00000000000000000e+00,
        ur: 1.0,
        tand: 0.00000000000000000e+00,
        cond: 0.00000000000000000e+00,
        tet_indices: vec![0],
        er_diag: None,
        ur_diag: None,
        dispersion: Dispersion::None,
    };
    let (er_t, _ur_t) = build_material_tensors(1, &[mat], 1.00000000000000000e+10);
    let want_re = 1.00000000000000000e+00;
    let want_im = 0.00000000000000000e+00;
    let mut max_err = 0.0_f64;
    // Isotropic: all three diagonal entries carry the same complex εr*.
    for k in 0..3 {
        let v = er_t[0][k][k];
        let er = rel_err(v.re, want_re);
        let ei = rel_err(v.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "air εr* re mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.re, want_re, er);
        assert!(ei < 1e-12, "air εr* im mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.im, want_im, ei);
    }
    eprintln!("dielectric air: max rel err {:.2e}", max_err);
}

// ===== dielectric low_freq_cond: er=3.0, tand=0.01, sigma=0.5, f=1000000.0 =====
#[test]
fn lossy_dielectric_matches_closed_form_low_freq_cond() {
    let mat = Material {
        er: 3.00000000000000000e+00,
        ur: 1.0,
        tand: 1.00000000000000002e-02,
        cond: 5.00000000000000000e-01,
        tet_indices: vec![0],
        er_diag: None,
        ur_diag: None,
        dispersion: Dispersion::None,
    };
    let (er_t, _ur_t) = build_material_tensors(1, &[mat], 1.00000000000000000e+06);
    let want_re = 3.00000000000000000e+00;
    let want_im = -8.98758178615659017e+03;
    let mut max_err = 0.0_f64;
    // Isotropic: all three diagonal entries carry the same complex εr*.
    for k in 0..3 {
        let v = er_t[0][k][k];
        let er = rel_err(v.re, want_re);
        let ei = rel_err(v.im, want_im);
        max_err = max_err.max(er).max(ei);
        assert!(er < 1e-12, "low_freq_cond εr* re mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.re, want_re, er);
        assert!(ei < 1e-12, "low_freq_cond εr* im mismatch [{}]: got {:.17e} want {:.17e} (rel {:.2e})", k, v.im, want_im, ei);
    }
    eprintln!("dielectric low_freq_cond: max rel err {:.2e}", max_err);
}
