// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/nedelec2/emit_interp_golden.py — do not edit.
// Golden field/curl reconstruction values from the independent symbolic R2
// element (element.py). Each case sets ONE canonical DOF to 1 (rest 0), so the
// reconstructed field equals RECON_SIGN*phi_i and its curl equals
// RECON_SIGN*(curl phi_i) exactly. Pins `interp::eval_field_in_tet` and
// `eval_curl_in_tet` to the derivation, entrywise, at interior sample points.

use num_complex::Complex64 as C64;
use rapidfem_fd::basis::NedelecBasis;
use rapidfem_fd::interp::{eval_curl_in_tet, eval_field_in_tet};
use rapidfem_fd::mesh::Mesh;

const NODES: [[f64; 3]; 4] = [
    [1.00000000000000006e-01, 2.00000000000000011e-01, 2.99999999999999989e-01],
    [1.30000000000000004e+00, 1.00000000000000006e-01, 2.00000000000000011e-01],
    [2.00000000000000011e-01, 1.10000000000000009e+00, 4.00000000000000022e-01],
    [2.99999999999999989e-01, 2.50000000000000000e-01, 1.19999999999999996e+00]
];

fn build_mesh() -> Mesh {
    let nodes = vec![NODES[0], NODES[1], NODES[2], NODES[3]];
    let tets = vec![[0usize, 1, 2, 3]];
    Mesh::from_tets(nodes, tets)
}

/// Set local DOF `local_dof` to 1 (rest 0) and pin the reconstructed field and
/// curl at every sample point against the symbolic golden values.
fn check_dof(local_dof: usize, pts: &[[f64; 3]], e_exp: &[[f64; 3]], curl_exp: &[[f64; 3]]) {
    let mesh = build_mesh();
    let basis = NedelecBasis::new(&mesh);
    assert_eq!(basis.n_field, 20);
    // Single-tet mesh: tet_dofs(0) is the identity, but route through it
    // anyway so the test stays correct under any DOF-numbering change.
    let mut sol = vec![C64::new(0.0, 0.0); basis.n_field];
    sol[basis.tet_dofs(0)[local_dof]] = C64::new(1.0, 0.0);

    for (pi, p) in pts.iter().enumerate() {
        let (ex, ey, ez) = eval_field_in_tet(&mesh, &basis, &sol, 0, p[0], p[1], p[2]);
        let got = [ex, ey, ez];
        let scale = e_exp[pi].iter().fold(1e-12_f64, |m, &v| m.max(v.abs()));
        for k in 0..3 {
            let diff = (got[k].re - e_exp[pi][k]).abs();
            assert!(
                diff / scale < 1e-9,
                "E dof {local_dof} pt {pi} comp {k}: got {} exp {} rel {:.2e}",
                got[k].re, e_exp[pi][k], diff / scale
            );
            assert!(got[k].im.abs() < 1e-12, "E imag dof {local_dof} pt {pi} comp {k}: {}", got[k].im);
        }
        let curl = eval_curl_in_tet(&mesh, &basis, &sol, 0, p[0], p[1], p[2]);
        let cscale = curl_exp[pi].iter().fold(1e-12_f64, |m, &v| m.max(v.abs()));
        for k in 0..3 {
            let diff = (curl[k].re - curl_exp[pi][k]).abs();
            assert!(
                diff / cscale < 1e-9,
                "curl dof {local_dof} pt {pi} comp {k}: got {} exp {} rel {:.2e}",
                curl[k].re, curl_exp[pi][k], diff / cscale
            );
            assert!(curl[k].im.abs() < 1e-12, "curl imag dof {local_dof} pt {pi} comp {k}: {}", curl[k].im);
        }
    }
}
const PTS: [[f64; 3]; 3] = [
    [4.74999999999999978e-01, 4.12499999999999978e-01, 5.25000000000000022e-01],
    [5.00000000000000000e-01, 3.54999999999999982e-01, 3.80000000000000004e-01],
    [4.50000000000000011e-01, 4.69999999999999973e-01, 6.70000000000000040e-01]
];

// ===== DOF 0 (edge_m1_e0) =====
const E_D0: [[f64; 3]; 3] = [
    [-5.41327778978555441e-01, -2.53127919184338579e-01, -2.01282441761040320e-01],
    [-7.47794768481925609e-01, -2.95214247916192496e-01, -2.20190792350713815e-01],
    [-3.34860789475185272e-01, -2.11041590452484690e-01, -1.82374091171366826e-01]
];
const CURL_D0: [[f64; 3]; 3] = [
    [-2.43978717286109481e-01, 2.07381909693193078e+00, -1.95182973828887585e+00],
    [-2.43978717286109481e-01, 2.07381909693193078e+00, -1.95182973828887585e+00],
    [-2.43978717286109481e-01, 2.07381909693193078e+00, -1.95182973828887585e+00]
];

#[test]
fn interp_recon_dof_0_edge_m1_e0() {
    check_dof(0, &PTS, &E_D0, &CURL_D0);
}

// ===== DOF 14 (edge_m2_e4_reversed) =====
const E_D14: [[f64; 3]; 3] = [
    [-3.17667704396647765e-01, 7.17893117280559850e-02, -3.28436101155856142e-01],
    [-1.50039661511637029e-01, 6.60461667898115112e-02, -4.44375839596666600e-01],
    [-4.85295747281658474e-01, 7.75324566663004727e-02, -2.12496362715045739e-01]
];
const CURL_D14: [[f64; 3]; 3] = [
    [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00],
    [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00],
    [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00]
];

#[test]
fn interp_recon_dof_14_edge_m2_e4_reversed() {
    check_dof(14, &PTS, &E_D14, &CURL_D14);
}

// ===== DOF 8 (face_m1_f2_reversed) =====
const E_D8: [[f64; 3]; 3] = [
    [6.11733170691896658e-02, 4.48604325174057558e-02, 1.12151081293514393e-01],
    [3.60747789802307040e-02, 1.06266790794478060e-02, 1.45277888994029852e-01],
    [7.38274546572163376e-02, 6.46922393082173391e-02, 8.25898040736031125e-02]
];
const CURL_D8: [[f64; 3]; 3] = [
    [-5.12690657341780098e-01, 5.82603019706568262e-02, 2.56345328670890049e-01],
    [-6.43193733756051378e-01, 1.44485548887228921e-01, 1.49146373044881486e-01],
    [-3.82187580927508763e-01, -2.79649449459152787e-02, 3.63544284296898612e-01]
];

#[test]
fn interp_recon_dof_8_face_m1_f2_reversed() {
    check_dof(8, &PTS, &E_D8, &CURL_D8);
}

// ===== DOF 19 (face_m2_f3) =====
const E_D19: [[f64; 3]; 3] = [
    [6.81474003028773312e-02, -1.10739525492175667e-01, -8.99167087329631569e-03],
    [2.05199394245330624e-02, -5.20949015648662292e-02, -1.66582534073700145e-03],
    [1.35991923271075205e-01, -1.45986875315497228e-01, -2.21100454316002018e-02]
];
const CURL_D19: [[f64; 3]; 3] = [
    [3.40737001514386684e-01, 2.65017667844522964e-01, -6.81474003028773367e-01],
    [5.14891468955073206e-01, 2.12014134275618382e-01, -2.87733467945482102e-01],
    [1.66582534073700161e-01, 3.18021201413427546e-01, -1.07521453811206458e+00]
];

#[test]
fn interp_recon_dof_19_face_m2_f3() {
    check_dof(19, &PTS, &E_D19, &CURL_D19);
}
