// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/waveguide/emit_waveguide_golden.py — do not edit.
// Golden modal quantities for the analytic RectWaveguide port, pinned against
// closed-form rectangular-waveguide theory (Pozar, Microwave Engineering §3.3):
//   beta = sqrt(er*k0^2 - (m*pi/a)^2 - (n*pi/b)^2)   (3.119)
//   Z_TE = omega*mu0/beta                            (3.22)
//   transverse TE_mn E-field profile at sample points.
// Excitation is built as the solver does, Excitation::new(freq, 1.0) (physical
// units, l0 = 1 so k0 is the physical free-space wavenumber).
#![allow(non_upper_case_globals)]

use rapidfem_fd::waveguide::{CoordinateSystem, RectWaveguide};
use rapidfem_fd::excitation::Excitation;

fn rel(got: f64, exp: f64) -> f64 {
    (got - exp).abs() / exp.abs().max(1e-300)
}

// ===== case wr90_te10_10ghz: a=22.86mm b=10.16mm TE10 f=10GHz er=1 pol=1 =====
const SX_wr90_te10_10ghz: [f64; 6] = [2.85749999999999980e-03, 5.71499999999999959e-03, 8.57250000000000026e-03, 1.14299999999999992e-02, 1.42874999999999981e-02, 1.71450000000000005e-02];
const SY_wr90_te10_10ghz: [f64; 6] = [5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03];
const SZ_wr90_te10_10ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EX_wr90_te10_10ghz: [f64; 6] = [-0.00000000000000000e+00, -0.00000000000000000e+00, -0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EY_wr90_te10_10ghz: [f64; 6] = [1.12182163424890086e+03, 2.07285609402184537e+03, 2.70831700396724727e+03, 2.93146120101341285e+03, 2.70831700396724727e+03, 2.07285609402184446e+03];
const EZ_wr90_te10_10ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];

#[test]
fn rect_waveguide_matches_pozar_wr90_te10_10ghz() {
    let wg = RectWaveguide {
        port_number: 1,
        power: 1.00000000000000000e+00,
        mode: (1, 0),
        er: 1.00000000000000000e+00,
        polarization: 1.00000000000000000e+00,
        dims: (2.28599999999999984e-02, 1.01600000000000006e-02),
        cs: CoordinateSystem::new(
            [1.14299999999999992e-02, 5.08000000000000031e-03, 0.0],
            [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]),
    };
    let exc = Excitation::new(1.00000000000000000e+10, 1.0);

    // β  (Pozar 3.119)
    let beta_err = rel(wg.get_beta(&exc), 1.58238256313019718e+02);
    // Z_TE = ω μ0 / β  (Pozar 3.22)
    let z_err = rel(wg.z_mode(&exc), 4.98974375968110337e+02);
    // qmode = sqrt(Z_TE/Z0)
    let q_err = rel(wg.qmode(&exc), 1.15086355766110393e+00);
    // amplitude = sqrt(P·4·Z0/(a·b))
    let a_err = rel(wg.get_amplitude(&exc), 2.54718396590036400e+03);
    assert!(beta_err < 1e-9, "wr90_te10_10ghz beta rel err {:.2e}", beta_err);
    assert!(z_err < 1e-9, "wr90_te10_10ghz Z_TE rel err {:.2e}", z_err);
    assert!(q_err < 1e-9, "wr90_te10_10ghz qmode rel err {:.2e}", q_err);
    assert!(a_err < 1e-9, "wr90_te10_10ghz amplitude rel err {:.2e}", a_err);

    // Transverse modal E-field at sample cross-section points.
    let mut scale = 1e-300_f64;
    let mut fmax = 0.0_f64;
    for i in 0..SX_wr90_te10_10ghz.len() {
        let (ex, ey, ez) = wg.port_mode_3d_global(SX_wr90_te10_10ghz[i], SY_wr90_te10_10ghz[i], SZ_wr90_te10_10ghz[i], &exc);
        scale = scale.max(EX_wr90_te10_10ghz[i].abs()).max(EY_wr90_te10_10ghz[i].abs()).max(EZ_wr90_te10_10ghz[i].abs());
        fmax = fmax.max((ex - EX_wr90_te10_10ghz[i]).abs());
        fmax = fmax.max((ey - EY_wr90_te10_10ghz[i]).abs());
        fmax = fmax.max((ez - EZ_wr90_te10_10ghz[i]).abs());
    }
    let field_err = fmax / scale;
    eprintln!("wr90_te10_10ghz: beta {:.2e} Z {:.2e} q {:.2e} amp {:.2e} field {:.2e}",
        beta_err, z_err, q_err, a_err, field_err);
    assert!(field_err < 1e-6, "wr90_te10_10ghz field rel err {:.2e}", field_err);
}

// ===== case wr90_te10_12ghz: a=22.86mm b=10.16mm TE10 f=12GHz er=1 pol=1 =====
const SX_wr90_te10_12ghz: [f64; 6] = [2.85749999999999980e-03, 5.71499999999999959e-03, 8.57250000000000026e-03, 1.14299999999999992e-02, 1.42874999999999981e-02, 1.71450000000000005e-02];
const SY_wr90_te10_12ghz: [f64; 6] = [5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03];
const SZ_wr90_te10_12ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EX_wr90_te10_12ghz: [f64; 6] = [-0.00000000000000000e+00, -0.00000000000000000e+00, -0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EY_wr90_te10_12ghz: [f64; 6] = [1.06513841730949662e+03, 1.96811916608741990e+03, 2.57147161287320114e+03, 2.78334081704725486e+03, 2.57147161287320114e+03, 1.96811916608741899e+03];
const EZ_wr90_te10_12ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];

#[test]
fn rect_waveguide_matches_pozar_wr90_te10_12ghz() {
    let wg = RectWaveguide {
        port_number: 1,
        power: 1.00000000000000000e+00,
        mode: (1, 0),
        er: 1.00000000000000000e+00,
        polarization: 1.00000000000000000e+00,
        dims: (2.28599999999999984e-02, 1.01600000000000006e-02),
        cs: CoordinateSystem::new(
            [1.14299999999999992e-02, 5.08000000000000031e-03, 0.0],
            [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]),
    };
    let exc = Excitation::new(1.20000000000000000e+10, 1.0);

    // β  (Pozar 3.119)
    let beta_err = rel(wg.get_beta(&exc), 2.10633895011129084e+02);
    // Z_TE = ω μ0 / β  (Pozar 3.22)
    let z_err = rel(wg.z_mode(&exc), 4.49824099927881718e+02);
    // qmode = sqrt(Z_TE/Z0)
    let q_err = rel(wg.qmode(&exc), 1.09271291524615721e+00);
    // amplitude = sqrt(P·4·Z0/(a·b))
    let a_err = rel(wg.get_amplitude(&exc), 2.54718396590036400e+03);
    assert!(beta_err < 1e-9, "wr90_te10_12ghz beta rel err {:.2e}", beta_err);
    assert!(z_err < 1e-9, "wr90_te10_12ghz Z_TE rel err {:.2e}", z_err);
    assert!(q_err < 1e-9, "wr90_te10_12ghz qmode rel err {:.2e}", q_err);
    assert!(a_err < 1e-9, "wr90_te10_12ghz amplitude rel err {:.2e}", a_err);

    // Transverse modal E-field at sample cross-section points.
    let mut scale = 1e-300_f64;
    let mut fmax = 0.0_f64;
    for i in 0..SX_wr90_te10_12ghz.len() {
        let (ex, ey, ez) = wg.port_mode_3d_global(SX_wr90_te10_12ghz[i], SY_wr90_te10_12ghz[i], SZ_wr90_te10_12ghz[i], &exc);
        scale = scale.max(EX_wr90_te10_12ghz[i].abs()).max(EY_wr90_te10_12ghz[i].abs()).max(EZ_wr90_te10_12ghz[i].abs());
        fmax = fmax.max((ex - EX_wr90_te10_12ghz[i]).abs());
        fmax = fmax.max((ey - EY_wr90_te10_12ghz[i]).abs());
        fmax = fmax.max((ez - EZ_wr90_te10_12ghz[i]).abs());
    }
    let field_err = fmax / scale;
    eprintln!("wr90_te10_12ghz: beta {:.2e} Z {:.2e} q {:.2e} amp {:.2e} field {:.2e}",
        beta_err, z_err, q_err, a_err, field_err);
    assert!(field_err < 1e-6, "wr90_te10_12ghz field rel err {:.2e}", field_err);
}

// ===== case wr90_te20_20ghz: a=22.86mm b=10.16mm TE20 f=20GHz er=1 pol=1 =====
const SX_wr90_te20_20ghz: [f64; 6] = [2.85749999999999980e-03, 5.71499999999999959e-03, 8.57250000000000026e-03, 1.14299999999999992e-02, 1.42874999999999981e-02, 1.71450000000000005e-02];
const SY_wr90_te20_20ghz: [f64; 6] = [5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03];
const SZ_wr90_te20_20ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EX_wr90_te20_20ghz: [f64; 6] = [-0.00000000000000000e+00, -0.00000000000000000e+00, -0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EY_wr90_te20_20ghz: [f64; 6] = [-2.07285609402184627e+03, 1.79500228832286602e-13, 2.07285609402184627e+03, 2.93146120101341285e+03, 2.07285609402184627e+03, -1.77324520386395653e-12];
const EZ_wr90_te20_20ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];

#[test]
fn rect_waveguide_matches_pozar_wr90_te20_20ghz() {
    let wg = RectWaveguide {
        port_number: 1,
        power: 1.00000000000000000e+00,
        mode: (2, 0),
        er: 1.00000000000000000e+00,
        polarization: 1.00000000000000000e+00,
        dims: (2.28599999999999984e-02, 1.01600000000000006e-02),
        cs: CoordinateSystem::new(
            [1.14299999999999992e-02, 5.08000000000000031e-03, 0.0],
            [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]),
    };
    let exc = Excitation::new(2.00000000000000000e+10, 1.0);

    // β  (Pozar 3.119)
    let beta_err = rel(wg.get_beta(&exc), 3.16476512626039437e+02);
    // Z_TE = ω μ0 / β  (Pozar 3.22)
    let z_err = rel(wg.z_mode(&exc), 4.98974375968110337e+02);
    // qmode = sqrt(Z_TE/Z0)
    let q_err = rel(wg.qmode(&exc), 1.15086355766110393e+00);
    // amplitude = sqrt(P·4·Z0/(a·b))
    let a_err = rel(wg.get_amplitude(&exc), 2.54718396590036400e+03);
    assert!(beta_err < 1e-9, "wr90_te20_20ghz beta rel err {:.2e}", beta_err);
    assert!(z_err < 1e-9, "wr90_te20_20ghz Z_TE rel err {:.2e}", z_err);
    assert!(q_err < 1e-9, "wr90_te20_20ghz qmode rel err {:.2e}", q_err);
    assert!(a_err < 1e-9, "wr90_te20_20ghz amplitude rel err {:.2e}", a_err);

    // Transverse modal E-field at sample cross-section points.
    let mut scale = 1e-300_f64;
    let mut fmax = 0.0_f64;
    for i in 0..SX_wr90_te20_20ghz.len() {
        let (ex, ey, ez) = wg.port_mode_3d_global(SX_wr90_te20_20ghz[i], SY_wr90_te20_20ghz[i], SZ_wr90_te20_20ghz[i], &exc);
        scale = scale.max(EX_wr90_te20_20ghz[i].abs()).max(EY_wr90_te20_20ghz[i].abs()).max(EZ_wr90_te20_20ghz[i].abs());
        fmax = fmax.max((ex - EX_wr90_te20_20ghz[i]).abs());
        fmax = fmax.max((ey - EY_wr90_te20_20ghz[i]).abs());
        fmax = fmax.max((ez - EZ_wr90_te20_20ghz[i]).abs());
    }
    let field_err = fmax / scale;
    eprintln!("wr90_te20_20ghz: beta {:.2e} Z {:.2e} q {:.2e} amp {:.2e} field {:.2e}",
        beta_err, z_err, q_err, a_err, field_err);
    assert!(field_err < 1e-6, "wr90_te20_20ghz field rel err {:.2e}", field_err);
}

// ===== case diel_te10_8ghz: a=22.86mm b=10.16mm TE10 f=8GHz er=2.2 pol=-1 =====
const SX_diel_te10_8ghz: [f64; 6] = [2.85749999999999980e-03, 5.71499999999999959e-03, 8.57250000000000026e-03, 1.14299999999999992e-02, 1.42874999999999981e-02, 1.71450000000000005e-02];
const SY_diel_te10_8ghz: [f64; 6] = [5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03, 5.08000000000000031e-03];
const SZ_diel_te10_8ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];
const EX_diel_te10_8ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, -0.00000000000000000e+00, -0.00000000000000000e+00, -0.00000000000000000e+00];
const EY_diel_te10_8ghz: [f64; 6] = [-6.19927516884937745e+02, -1.14547668898107872e+03, -1.49663741895189310e+03, -1.61994866893926906e+03, -1.49663741895189310e+03, -1.14547668898107804e+03];
const EZ_diel_te10_8ghz: [f64; 6] = [0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00];

#[test]
fn rect_waveguide_matches_pozar_diel_te10_8ghz() {
    let wg = RectWaveguide {
        port_number: 1,
        power: 5.00000000000000000e-01,
        mode: (1, 0),
        er: 2.20000000000000018e+00,
        polarization: -1.00000000000000000e+00,
        dims: (2.28599999999999984e-02, 1.01600000000000006e-02),
        cs: CoordinateSystem::new(
            [1.14299999999999992e-02, 5.08000000000000031e-03, 0.0],
            [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]),
    };
    let exc = Excitation::new(8.00000000000000000e+09, 1.0);

    // β  (Pozar 3.119)
    let beta_err = rel(wg.get_beta(&exc), 2.07270394638565449e+02);
    // Z_TE = ω μ0 / β  (Pozar 3.22)
    let z_err = rel(wg.z_mode(&exc), 3.04749109339052382e+02);
    // qmode = sqrt(Z_TE/Z0)
    let q_err = rel(wg.qmode(&exc), 8.99406328177149939e-01);
    // amplitude = sqrt(P·4·Z0/(a·b))
    let a_err = rel(wg.get_amplitude(&exc), 1.80113105521779107e+03);
    assert!(beta_err < 1e-9, "diel_te10_8ghz beta rel err {:.2e}", beta_err);
    assert!(z_err < 1e-9, "diel_te10_8ghz Z_TE rel err {:.2e}", z_err);
    assert!(q_err < 1e-9, "diel_te10_8ghz qmode rel err {:.2e}", q_err);
    assert!(a_err < 1e-9, "diel_te10_8ghz amplitude rel err {:.2e}", a_err);

    // Transverse modal E-field at sample cross-section points.
    let mut scale = 1e-300_f64;
    let mut fmax = 0.0_f64;
    for i in 0..SX_diel_te10_8ghz.len() {
        let (ex, ey, ez) = wg.port_mode_3d_global(SX_diel_te10_8ghz[i], SY_diel_te10_8ghz[i], SZ_diel_te10_8ghz[i], &exc);
        scale = scale.max(EX_diel_te10_8ghz[i].abs()).max(EY_diel_te10_8ghz[i].abs()).max(EZ_diel_te10_8ghz[i].abs());
        fmax = fmax.max((ex - EX_diel_te10_8ghz[i]).abs());
        fmax = fmax.max((ey - EY_diel_te10_8ghz[i]).abs());
        fmax = fmax.max((ez - EZ_diel_te10_8ghz[i]).abs());
    }
    let field_err = fmax / scale;
    eprintln!("diel_te10_8ghz: beta {:.2e} Z {:.2e} q {:.2e} amp {:.2e} field {:.2e}",
        beta_err, z_err, q_err, a_err, field_err);
    assert!(field_err < 1e-6, "diel_te10_8ghz field rel err {:.2e}", field_err);
}
