# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
"""Emit the Rust golden test for the Debye dispersion model.

Pins `rapidfem_core::materials::Dispersion::Debye::evaluate` to its exact
closed form. The Debye permittivity is the Laplace transform of the auxiliary
differential equation evaluated at s = jω, so the ground truth is analytic and
exact (no numerical derivation required):

    ε(ω) = ε∞ + (εs - ε∞) / (1 + jωτ),    ω = 2π f

The Rust code uses the e^{+jωt} time convention (denominator 1 + jωτ), giving a
non-positive imaginary part (loss). We mirror that convention here.
"""
from __future__ import annotations

import os

import mpmath as mp

mp.mp.dps = 40  # 40 significant decimal digits — well beyond f64

# (name, er_inf, er_static, tau_s)
CASES = [
    ("water_like", 4.9, 78.4, 8.27e-12),
    ("low_loss", 2.1, 2.1, 1.0e-9),          # er_inf == er_static -> non-dispersive
    ("high_contrast", 1.0, 100.0, 1.0e-6),
    ("negative_drop", 12.0, 3.0, 2.5e-10),   # er_static < er_inf
]

# Frequencies in Hz, spanning below/around/above the relaxation knee.
FREQS = [1.0e6, 1.0e9, 2.4e9, 6.0e10, 3.0e11]

TWO_PI = 2 * mp.pi


def debye_eps(er_inf, er_static, tau_s, freq):
    omega = TWO_PI * freq
    return er_inf + (er_static - er_inf) / (1 + 1j * omega * tau_s)


def f64(v):
    return f"{float(v):.17e}"


HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/materials/emit_debye_golden.py — do not edit.
// Golden complex relative permittivity for the Debye dispersion model.
// Pins rapidfem_core::materials::Dispersion::Debye::evaluate to the exact
// closed form  ε(ω) = ε∞ + (εs - ε∞)/(1 + jωτ),  ω = 2π f  (e^{+jωt}).

use rapidfem_core::materials::Dispersion;

fn rel_err(got: f64, want: f64) -> f64 {
    let scale = want.abs().max(1e-300);
    (got - want).abs() / scale
}
"""


def emit_case(name, er_inf, er_static, tau_s):
    out = f"\n// ===== case {name}: er_inf={er_inf}, er_static={er_static}, tau_s={tau_s} =====\n"
    out += "#[test]\n"
    out += f"fn debye_matches_closed_form_{name}() {{\n"
    out += "    let disp = Dispersion::Debye {\n"
    out += f"        er_inf: {f64(er_inf)},\n"
    out += f"        er_static: {f64(er_static)},\n"
    out += f"        tau_s: {f64(tau_s)},\n"
    out += "    };\n"
    out += "    // (frequency_hz, want_re, want_im)\n"
    out += "    let table: &[(f64, f64, f64)] = &[\n"
    for freq in FREQS:
        z = debye_eps(er_inf, er_static, tau_s, freq)
        out += f"        ({f64(freq)}, {f64(z.real)}, {f64(z.imag)}),\n"
    out += "    ];\n"
    out += "    let mut max_err = 0.0_f64;\n"
    out += "    for &(freq, want_re, want_im) in table {\n"
    out += "        // base_er is unused by the Debye branch; pass a dummy value.\n"
    out += "        let z = disp.evaluate(1.0, freq);\n"
    out += "        let er = rel_err(z.re, want_re);\n"
    out += "        let ei = rel_err(z.im, want_im);\n"
    out += "        max_err = max_err.max(er).max(ei);\n"
    out += f'        assert!(er < 1e-12, "{name} re mismatch @ {{:.3e}} Hz: got {{:.17e}} want {{:.17e}} (rel {{:.2e}})", freq, z.re, want_re, er);\n'
    out += f'        assert!(ei < 1e-12, "{name} im mismatch @ {{:.3e}} Hz: got {{:.17e}} want {{:.17e}} (rel {{:.2e}})", freq, z.im, want_im, ei);\n'
    out += "    }\n"
    out += f'    eprintln!("{name}: max rel err {{:.2e}}", max_err);\n'
    out += "}\n"
    return out


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    out_path = os.path.join(repo, "crates", "rapidfem-core", "tests", "debye_golden_test.rs")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    body = HEADER
    for name, er_inf, er_static, tau_s in CASES:
        body += emit_case(name, er_inf, er_static, tau_s)
        print(f"emitted case {name}")
    with open(out_path, "w") as fh:
        fh.write(body)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
