// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/td_dg/emit_propagator_golden.py - do not edit.
// Golden reference for the Krylov exponential propagator (propagator.rs).
//
// dy/dt = A*y has the EXACT propagator exp(h*A). A is a 6x6
// skew-symmetric wave operator [[0,-L],[L,0]], L = tridiag(-1,2,-1),
// so every eigenvalue is on the imaginary axis (oscillatory, energy-
// conserving). The reference exp(h*A)*v0 is computed by EXACT sympy
// matrix exponentiation, (h*A).exp(), at 30-digit precision. For a
// 6-dim system a Krylov dimension m >= 6 spans the whole space, so the
// Arnoldi projection is exact bar the dense exp(h*H_m) and round-off.

use rapidfem_td::propagator::expmv;

const N: usize = 6;

// Row-major 6x6 operator A.
const A: [f64; 36] = [0.0, 0.0, 0.0, -2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -2.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 2.0, 0.0, 0.0, 0.0];
// Test vector v0.
const V0: [f64; 6] = [0.14285714285714285, 0.2857142857142857, 0.42857142857142855, 0.5714285714285714, 0.7142857142857143, 0.8571428571428571];

const H0: f64 = 0.1;
const REF0: [f64; 6] = [0.10053436023237161, 0.28759154261219044, 0.32379071653128033, 0.567098636031954, 0.7217242358211068, 0.9038803242137549];
const H1: f64 = 0.3;
const REF1: [f64; 6] = [0.028661444636115446, 0.28446177230937447, 0.10314519935458485, 0.5344722021688811, 0.7817982206011413, 0.9316087988273707];
const H2: f64 = 1.0;
const REF2: [f64; 6] = [0.04336636058341353, -0.1721389323094955, -0.3353320003802505, 0.46040173633669706, 1.067543494970224, 0.6013019049877083];

/// Matrix-free A*x for the dense row-major A above.
fn matvec(x: &[f64]) -> Vec<f64> {
    let mut ax = vec![0.0; N];
    for i in 0..N {
        let mut s = 0.0;
        for j in 0..N {
            s += A[i * N + j] * x[j];
        }
        ax[i] = s;
    }
    ax
}

fn rel_err(got: &[f64], want: &[f64]) -> f64 {
    let num: f64 = got
        .iter()
        .zip(want)
        .map(|(g, w)| (g - w).powi(2))
        .sum::<f64>()
        .sqrt();
    let scale: f64 = want.iter().map(|w| w * w).sum::<f64>().sqrt();
    num / scale.max(1e-300)
}

#[test]
fn propagator_matches_exact_matrix_exponential() {
    // Krylov dimension covering the whole 6-dim space makes
    // the projection exact; m = 12 (>= N) with the early
    // lucky-breakdown stop runs at most N steps anyway.
    let m = 12;

    let got = expmv(matvec, &V0, H0, m);
    let err = rel_err(&got, &REF0);
    eprintln!("h = {:.3}: rel err vs exp(hA)*v0 = {:.2e}", H0, err);
    assert!(err < 1e-10, "h = {}: rel err {:.2e}", H0, err);

    let got = expmv(matvec, &V0, H1, m);
    let err = rel_err(&got, &REF1);
    eprintln!("h = {:.3}: rel err vs exp(hA)*v0 = {:.2e}", H1, err);
    assert!(err < 1e-10, "h = {}: rel err {:.2e}", H1, err);

    let got = expmv(matvec, &V0, H2, m);
    let err = rel_err(&got, &REF2);
    eprintln!("h = {:.3}: rel err vs exp(hA)*v0 = {:.2e}", H2, err);
    assert!(err < 1e-10, "h = {}: rel err {:.2e}", H2, err);
}

