// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2024-2026 Milan Rother and rapidfem contributors
//
// GENERATED by derivations/td_dg/emit_rhs_curl_golden.py — do not edit.
// Golden for the DGTD physical curl operator (rhs.rs, `element_curl`).
//
// A vector field E with degree-<=p polynomial components, sampled at the DG
// nodes of a concrete physical tetrahedron, is fed into the real curl
// operator; the result must equal the EXACT analytic curl(E) sampled at the
// same nodes. The affine map pulls a degree-d physical polynomial back to a
// degree-d reference polynomial, the nodal-DG diff matrices Dr/Ds/Dt are
// exact to degree p, and the constant J^-1 metric converts reference
// derivatives to physical ones with no error — so the operator reproduces
// curl(E) to rounding. Field / output layout is node-major
// `v[node*3 + comp]`, comp = x,y,z, matching rhs.rs.

use rapidfem_td::dg_basis::ReferenceElement;
use rapidfem_td::geom_factors::GeometricFactors;
use rapidfem_td::rhs::element_curl;

/// Max entrywise absolute difference divided by the max magnitude in the
/// golden vector (global relative error).
fn max_rel_err(got: &[f64], want: &[f64]) -> f64 {
    assert_eq!(got.len(), want.len(), "length mismatch");
    let mut num = 0.0_f64;
    let mut scale = 1e-300_f64;
    for (g, w) in got.iter().zip(want.iter()) {
        scale = scale.max(w.abs());
        num = num.max((g - w).abs());
    }
    num / scale
}

// ===== order p = 2  (Np = 10) =====
const TET: [[f64; 3]; 4] = [[1.00000000000000000e+00, 0.00000000000000000e+00, 0.00000000000000000e+00], [2.00000000000000000e+00, 5.00000000000000000e-01, 0.00000000000000000e+00], [5.00000000000000000e-01, 2.00000000000000000e+00, 2.99999999999999989e-01], [0.00000000000000000e+00, 2.00000000000000011e-01, 3.00000000000000000e+00]];
const FIELD: [f64; 30] = [1.00000000000000000e+00, 1.00000000000000000e+00, -2.00000000000000000e+00, -1.19999999999999996e+00, -1.22999999999999998e+00, 4.00000000000000022e-01, -7.20000000000000018e+00, 3.08000000000000007e+00, 4.00000000000000022e-01, 2.67750000000000021e+00, 2.26250000000000018e+00, 4.98749999999999982e+00, 3.52249999999999996e+00, 2.48249999999999993e+00, 7.43750000000000000e+00, 4.20999999999999996e+00, 7.95000000000000018e+00, 2.16499999999999986e+01, 2.25000000000000000e+00, 2.37500000000000000e+00, -3.93750000000000000e+00, 1.02499999999999991e+00, -3.25499999999999989e+00, 4.62500000000000022e-01, 4.91500000000000004e+00, 4.08750000000000036e+00, 6.12500000000000000e+00, 4.00000000000000000e+00, 4.50000000000000000e+00, -6.25000000000000000e+00];
const CURL: [f64; 30] = [4.00000000000000000e+00, 4.00000000000000000e+00, 0.00000000000000000e+00, 3.00000000000000000e+00, -2.20000000000000018e+00, -1.05000000000000000e+01, 2.00000000000000000e+00, -8.40000000000000036e+00, -2.10000000000000000e+01, 1.30000000000000000e+01, 5.54999999999999982e+00, -1.05000000000000004e+00, 1.20000000000000000e+01, -6.50000000000000022e-01, -1.15500000000000007e+01, 2.20000000000000000e+01, 7.09999999999999964e+00, -2.10000000000000009e+00, 8.50000000000000000e+00, 6.75000000000000000e+00, 0.00000000000000000e+00, 7.50000000000000000e+00, 5.50000000000000044e-01, -1.05000000000000000e+01, 1.75000000000000000e+01, 8.30000000000000071e+00, -1.05000000000000004e+00, 1.30000000000000000e+01, 9.50000000000000000e+00, 0.00000000000000000e+00];

#[test]
fn rhs_curl_matches_exact_polynomial_curl() {
    let re = ReferenceElement::new(2);
    assert_eq!(re.n_nodes, 10, "Np for p=2");
    let gf = GeometricFactors::for_tet(&TET);
    let got = element_curl(&re, &gf, &FIELD);
    let err = max_rel_err(&got, &CURL);
    eprintln!("rhs curl: max rel err {:.2e}", err);
    assert!(err < 1e-9, "curl mismatch: {:.2e}", err);
}
